### ISSUE TITLE
Add a license.

### ISSUE THREAD

**Issue by voithos** [canisbos/Pickpocket#5]
It would be nice if you added a license to this project, or otherwise specified the terms of modification. It'd be generally helpful for anyone thinking about contributing code, etc. [http://choosealicense.com/](http://choosealicense.com/) is a simple way to explore the different options.

**Comment by canisbos** [comment]
Done. MIT License.

**Comment by voithos** [comment]
Thanks! :)
Just FYI, you forgot to replace the `<year>` and `<copyright holders>` sections of the file.

**Comment by canisbos** [comment]
Bummer!
